site_name: Довідка AEDOC
site_description: Документація АЕДок та еАкциз
site_url: https://dovidka.aedoc.com.ua/
copyright: © WebCheck — <a href="https://aedoc.com.ua">aedoc.com.ua</a>

theme:
  name: material
  language: uk
  logo: https://aedoc.com.ua/wp-content/uploads/2026/05/favicon-512x512-1.png
  favicon: https://aedoc.com.ua/wp-content/uploads/2026/05/favicon-512x512-1.png
  features:
    - navigation.sections
    - navigation.indexes
    - navigation.expand
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.highlight
  palette:
    primary: custom
    accent: custom

nav:
  - Головна: index.md
  - Інтеграція:
      - integratsiia/index.md
  - Перший запуск:
      - pershyi-zapusk/index.md
      - Реєстрація в еАкциз: pershyi-zapusk/reiestratsiia-eo.md
      - API-токен: pershyi-zapusk/api-token.md
  - Робота з АЕД:
      - aed/index.md
      - Прийняти вхідний АЕД: aed/pryiom-vkhidnoho-aed.md
  - Довідники:
      - dovidnyky/index.md

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/lightbox.js

markdown_extensions:
  - attr_list
  - admonition
  - md_in_html
  - tables
  - toc:
      permalink: true
